### ISSUE TITLE
AttributeError: 'numpy.float64' object has no attribute 'numerator'

### ISSUE THREAD

**Issue by LvWilliam** [Jeff-LiangF/streamv2v#11]
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/lvyihao/codes/streamv2v/vid2vid/main.py", line 191, in <module>
    fire.Fire(main)
  File "/opt/conda/envs/streamv2v/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/streamv2v/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/streamv2v/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/paddlejob/workspace/env_run/lvyihao/codes/streamv2v/vid2vid/main.py", line 187, in main
    write_video(output, video_result, fps=fps)
  File "/opt/conda/envs/streamv2v/lib/python3.10/site-packages/torchvision/io/video.py", line 92, in write_video
    stream = container.add_stream(video_codec, rate=fps)
  File "av/container/output.pyx", line 104, in av.container.output.OutputContainer.add_stream
  File "av/utils.pyx", line 51, in av.utils.to_avrational
AttributeError: 'numpy.float64' object has no attribute 'numerator'
I encounter this problem for the first time.

**Comment by Jeff-LiangF** [comment]
Hi, sorry for the late reply. Could you tell me how to reproduce your error? There are some common solutions with ChatGPT: https://chatgpt.com/share/6740f3df-2884-800f-a41e-6d5bc8e3e3cb. Feel free to reopen the issue if it doesn't fix your issue.

**Comment by pykao** [comment]
I ran `python main.py --input ./demo_selfie/jeff_1.mp4 --prompt "Elon Musk is giving a talk."`, and got the same error.

**Comment by Jeff-LiangF** [comment]
Hi @pykao ,

Thanks for sharing your env. My av is `12.0.0` and torchvision is `0.16.0+cu118`. Could you try this?

**Comment by pykao** [comment]
Hi @Jeff-LiangF ,

The error message did not show up after I downgrade my av version to `12.0.0`. Thanks for sharing.
